/** Declaration file generated by dts-gen */

interface Game {
  setRoles(roles: Array<any>): void

  next(): Game;
  restart(): Game;
}

export class Game {
    constructor(...args: any[]);

    next(...args: any[]): void;

    restart(...args: any[]): void;

}

